version: "3.7"
services:
    web:
        build: application
        restart: always
        ports:
            - 5000:5000
        links:
          - db
    db:
      image: mysql:8.0.22
      ports:
        - "32000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root@123
        
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro