version: "3.7"
services:
    application:
      build: application
      ports:
          - "5001:5001"
      links:
        - db
    db:
      image: mysql:8.0.22
      ports:
        - "32000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root@123

      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro